[package]
name = "pong"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Webb <matt.d.webb@icloud.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
find_folder = "*"
gfx_device_gl = "0.16.2"
